In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from feature_extraction import Featurizer
pd.set_option('display.max_columns', None)

In [ ]:
train_df = pd.read_csv("./train.csv")
test_df = pd.read_csv("./test.csv")

drop_cols = ["Name", "Age", "Ticket", "Cabin", "Embarked", "PassengerId"]
featurizer = Featurizer(drop_cols)
train_df, val_df = featurizer.get_train_features(train_df)

--Return--
> <ipython-input-4-175d9a48a6d7>(4)<module>()->None
-> breakpoint()
(Pdb) n
> /Users/sachinthaka/opt/miniconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3334)run_code()
-> sys.excepthook = old_excepthook
(Pdb) c
> /Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py(18)get_train_features()
-> train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)
(Pdb) df.shape
(891, 6)
(Pdb) df.head()
   Survived  Pclass     Sex  SibSp  Parch     Fare
0         0       3    male      1      0   7.2500
1         1       1  female      1      0  71.2833
2         1       3  female      0      0   7.9250
3         1       1  female      1      0  53.1000
4         0       3    male      0      0   8.0500
(Pdb) n
> /Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py(19)get_train_features()
-> train_df.reset_index(drop=True, inplace=True)
(Pdb) n
> /User

/Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df["Sex"] = self.le.fit_transform(train_df["Sex"])


> /Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py(23)get_train_features()
-> val_df["Sex"] = self.le.transform(val_df["Sex"])
(Pdb) n


/Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_df["Sex"] = self.le.transform(val_df["Sex"])


> /Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py(25)get_train_features()
-> onehot_vals = self.onehot.fit_transform(train_df["Pclass"].values[:, None]).todense()
(Pdb) n
> /Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py(26)get_train_features()
-> self.class_names = self.onehot.categories_[0][1:]
(Pdb) n
> /Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py(27)get_train_features()
-> pclass = pd.DataFrame(onehot_vals, columns=self.class_names)
(Pdb) self.class_names
array([2, 3])
(Pdb) train_df.head()
   Survived  Pclass  Sex  SibSp  Parch     Fare
0         1       3    1      0      2  20.5250
1         0       3    0      4      2  31.2750
2         0       1    1      0      0  32.3208
3         0       3    1      0      0   7.7292
4         0       3    1      0      0   7.8958
(Pdb) n
> /Users/sachinthaka/Google

/Users/sachinthaka/opt/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py:4164: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


> /Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py(29)get_train_features()
-> train_df = pd.concat([train_df, pclass], axis=1)
(Pdb) n
> /Users/sachinthaka/Google Drive/udemy_courses/python_data_science/04_classification/feature_extraction.py(31)get_train_features()
-> onehot_vals = self.onehot.transform(val_df["Pclass"].values[:, None]).todense()
(Pdb) train_df.head()
   Survived  Sex  SibSp  Parch     Fare    2    3
0         1    1      0      2  20.5250  0.0  1.0
1         0    0      4      2  31.2750  0.0  1.0
2         0    1      0      0  32.3208  0.0  0.0
3         0    1      0      0   7.7292  0.0  1.0
4         0    1      0      0   7.8958  0.0  1.0


In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [26]:
model = LogisticRegression()
model.fit(train_df.drop("Survived", axis=1), train_df["Survived"])
y_pred = model.predict(train_df.drop("Survived", axis=1))

In [29]:
model.predict_proba(train_df.drop("Survived", axis=1))

array([[0.89191127, 0.10808873],
       [0.62886612, 0.37113388],
       [0.61664039, 0.38335961],
       ...,
       [0.92476359, 0.07523641],
       [0.11031247, 0.88968753],
       [0.58866568, 0.41133432]])

In [31]:
import numpy as np
prob = model.predict_proba(train_df.drop("Survived", axis=1))
(prob[:,1] > 0.5).astype(np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,

In [18]:
accuracy_score(train_df["Survived"].values, y_pred)

0.7952559300873908

In [33]:
(train_df["Survived"].values == y_pred).mean()

0.7952559300873908

In [21]:
y_pred = model.predict(val_df.drop("Survived", axis=1))
accuracy_score(val_df["Survived"].values.squeeze(), y_pred.squeeze())

0.8222222222222222

In [9]:
from typing import Callable, Dict, List, Tuple

class Model():
    def __init__(
        self, 
        y_col: str,
        model: Callable, 
        metrics:Dict[str, Tuple[str, Callable]]=accuracy_score,
                ) -> None:
        self.model = model
        self.metrics = metrics
        self.y_col = y_col
        
    def print_metric(self, 
                     metric:Callable, 
                     metric_name: str,
                     metric_y_type: str,
                     df:pd.DataFrame, 
                     data_type:str) -> None:
        y_class = self.model.predict(df.drop(self.y_col, axis=1))
        y_prob = self.model.predict_proba(df.drop(self.y_col, axis=1))
        if metric_y_type == "prob":
            y_pred= y_prob
        else:
            y_pred = y_class
        metric_val = metric(df[self.y_col].values.squeeze(), y_pred.squeeze())
        print(f"{data_type} {metric_name}: {metric_val:.4f}")
        
    def fit(self, train_df: pd.DataFrame, val_df: pd.DataFrame) -> None:
        self.model.fit(train_df.drop(self.y_col, axis=1), train_df[self.y_col])
        
        for name, (metric_y_type, metric) in self.metrics.items():
            self.print_metric(metric, name, metric_y_type, train_df, "Training")
            self.print_metric(metric, name, metric_y_type, val_df, "Validation")

In [10]:
metric_list = {"Accuracy": ("class", accuracy_score)}

In [11]:
logistic = LogisticRegression()
model = Model("Survived", logistic, metric_list)
model.fit(train_df, val_df)

Training Accuracy: 0.7953
Validation Accuracy: 0.8222


In [12]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(n_estimators=50, max_depth=3)
model = Model("Survived", random_forest, metric_list)
model.fit(train_df, val_df)

Training Accuracy: 0.8127
Validation Accuracy: 0.8000


In [13]:
from sklearn.gaussian_process import GaussianProcessClassifier

gp = GaussianProcessClassifier()
model = Model("Survived", gp, metric_list)
model.fit(train_df, val_df)

Training Accuracy: 0.8764
Validation Accuracy: 0.7778


In [14]:
from sklearn import metrics

def auc(y, pred):
    fpr, tpr, _ = metrics.roc_curve(y, pred[:, 1])
    return metrics.auc(fpr, tpr)

In [15]:
metric_list["AUC"] = ("prob", auc)

In [16]:
for model_ in [logistic, random_forest, gp]:
    model = Model("Survived", model_, metric_list)
    model.fit(train_df, val_df)
    print("="*30)

Training Accuracy: 0.7953
Validation Accuracy: 0.8222
Training AUC: 0.8306
Validation AUC: 0.8840
Training Accuracy: 0.8140
Validation Accuracy: 0.8111
Training AUC: 0.8597
Validation AUC: 0.8827
Training Accuracy: 0.8764
Validation Accuracy: 0.7778
Training AUC: 0.8937
Validation AUC: 0.8228


In [23]:
train_df["Survived"].mean()

0.38202247191011235